export const tiles = [
  {name: " _ ", count: 2, points: 0},
  {name: "A", count: 9, points: 1},
  {name: "B", count: 2, points: 3},
  {name: "C", count: 2, points: 3},
  {name: "D", count: 4, points: 2},
  {name: "E", count: 12, points: 1},
  {name: "F", count: 2, points: 4},
  {name: "G", count: 3, points: 2},
  {name: "H", count: 2, points: 4},
  {name: "I", count: 9, points: 1},
  {name: "J", count: 1, points: 8},
  {name: "K", count: 1, points: 5},
  {name: "L", count: 4, points: 1},
  {name: "M", count: 2, points: 3},
  {name: "N", count: 6, points: 1},
  {name: "O", count: 8, points: 1},
  {name: "P", count: 2, points: 3},
  {name: "Q", count: 1, points: 10},
  {name: "R", count: 6, points: 1},
  {name: "S", count: 4, points: 1},
  {name: "T", count: 6, points: 1},
  {name: "U", count: 4, points: 1},
  {name: "V", count: 2, points: 4},
  {name: "W", count: 2, points: 4},
  {name: "X", count: 1, points: 8},
  {name: "Y", count: 2, points: 4},
  {name: "Z", count: 1, points: 10}
];
